services:
  bedrock-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: frank1o3/bedrock-server:beta
    container_name: bedrock-server

    # Load environment variables
    environment:
      - NO_IP_USERNAME
      - NO_IP_PASSWORD
    env_file:
      - .env

    # Networking
    network_mode: host # OR use the custom network below (choose one)
    # Restart policy
    restart: always

    # Volume mapping
    volumes:
      - ${HOME}/bedrock/backups:/bedrock/backups # Fixed path syntax
