services:
  bedrock-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: frank1o3/bedrock-server:latest
    container_name: bedrock-server
    environment:
      - NO_IP_USERNAME
      - NO_IP_PASSWORD
    env_file:
      - .env
    restart: always
    volumes:
      - ./backups:/bedrock/backups # Maps local directory to container directory
