services:
  bedrock-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: frank1o3/bedrock-server:beta
    container_name: bedrock-server

    # Load environment variables
    environment:
      - NO_IP_USERNAME
      - NO_IP_PASSWORD
    env_file:
      - .env

    # Restart policy
    restart: always

    # Volume mapping (replace USERNAME with a var in .env or hardcode the path)
    volumes:
      - ${HOME}/bedrock/backups:/bedrock/backups


    # Port mapping
    ports:
      - "19132:19132/tcp"
      - "19133:19133/tcp"
      - "19132:19132/udp"
      - "19133:19133/udp"
      - "5000:5000/tcp" # so user does not have to specify port in browser

    # Custom network
    networks:
      - net

# Setup of custom network called bedrock-network with default bridge driver
networks:
  net:
    driver: bridge
