name: Docker Compose CI/CD

on:
  schedule:
    - cron: '45 22 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: frank1o3/bedrock-server

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker compose version  # Verify installation

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push image using Docker Compose
        run: |
          docker compose build
          docker tag frank1o3/bedrock-server:latest ghcr.io/frank1o3/bedrock-server:latest
          docker push ghcr.io/frank1o3/bedrock-server:latest

      - name: Run Bedrock server container for testing
        run: |
          docker compose up -d
          sleep 10  # Give the server time to start
          docker ps

      - name: Stop and remove container
        run: docker compose down
